#!/usr/bin/env python3
"""Generate the Hotel Sense rooms dashboard (Lovelace YAML).

    python scripts/generate_dashboard.py > dashboards/hotel_sense_rooms.yaml

Rooms are given as HA area IDs (``room_01`` for an Area named "Room 01").
Check the IDs under Settings -> Areas if yours differ and pass them:

    python scripts/generate_dashboard.py --rooms room_01 room_02 --common admin_house

Only built-in cards are used (markdown + tile). A violation is a red
``ha-alert`` box, a staff visit in a checked-out room is blue.
"""
from __future__ import annotations

import argparse
import sys

DEFAULT_ROOMS = [f"room_{i:02d}" for i in range(1, 11)]
DEFAULT_COMMON = ["admin_house"]

STATE_LABELS = (
    "{'empty': 'Пусто', 'violation': 'НАРУШЕНИЕ', 'staff_visit': 'Визит сотрудника', "
    "'checked_in': 'Гость заселён'}"
)
ALERT_KINDS = (
    "{'violation': 'error', 'staff_visit': 'info'}"
)


def title_of(area_id: str) -> str:
    return " ".join(p.capitalize() if not p.isdigit() else p for p in area_id.split("_"))


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.splitlines())


def room_card(area_id: str) -> str:
    title = title_of(area_id)
    content = f"""\
{{%- set st = states('sensor.{area_id}_state') -%}}
{{%- set g = states('sensor.{area_id}_guest_devices') -%}}
{{%- set e = states('sensor.{area_id}_employee_devices') -%}}
{{%- set f = states('sensor.{area_id}_fixed_devices') -%}}
{{%- set label = {STATE_LABELS}.get(st, st) -%}}
{{%- set kind = {ALERT_KINDS}.get(st) -%}}
{{%- set line = 'Гости: ' ~ g ~ ' · Сотрудники: ' ~ e ~ ' · Фикс.: ' ~ f -%}}
{{% if kind %}}<ha-alert alert-type="{{{{ kind }}}}" title="{title} — {{{{ label }}}}">{{{{ line }}}}</ha-alert>
{{% else %}}**{title}** — {{{{ label }}}}<br>{{{{ line }}}}
{{% endif %}}
{{%- if state_attr('sensor.{area_id}_state', 'data_stale') %}}
<ha-alert alert-type="warning">Нет связи с контроллером: данные на момент потери связи</ha-alert>
{{%- endif %}}"""
    return f"""\
- type: vertical-stack
  cards:
    - type: markdown
      content: |
{_indent(content, 8)}
    - type: tile
      entity: select.{area_id}_status
      name: Статус
      hide_state: true
      features:
        - type: select-options
"""


def common_card(area_id: str) -> str:
    title = title_of(area_id)
    content = f"""\
**{title}**<br>
Гости: {{{{ states('sensor.{area_id}_guest_devices') }}}} · Сотрудники: {{{{ states('sensor.{area_id}_employee_devices') }}}} · Фикс.: {{{{ states('sensor.{area_id}_fixed_devices') }}}}"""
    return f"""\
- type: markdown
  content: |
{_indent(content, 4)}
"""


SUMMARY = """\
- type: markdown
  content: |
    {%- set v = integration_entities('hotel_sense') | select('match', 'binary_sensor\\\\..*_violation$') | select('is_state', 'on') | list -%}
    {% if v | count %}<ha-alert alert-type="error" title="Возможные нарушения: {{ v | count }}">{{ v | map('device_attr', 'name') | join(', ') }}</ha-alert>
    {% else %}<ha-alert alert-type="success">Нарушений нет</ha-alert>
    {% endif %}
    {%- set m = state_attr('sensor.hotel_sense_misplaced_devices', 'devices') or [] %}
    {%- if m %}
    <ha-alert alert-type="warning" title="Оборудование не на своём месте: {{ m | count }}">{% for d in m %}{{ d.name }}: ожидается {{ d.expected }}, видно в {{ d.seen }}<br>{% endfor %}</ha-alert>
    {%- endif %}
"""


def build_dashboard(rooms: list[str], common: list[str]) -> str:
    cards = SUMMARY + "".join(room_card(r) for r in rooms) + "".join(common_card(c) for c in common)
    return f"""\
# Hotel Sense - rooms matrix. Generated by scripts/generate_dashboard.py, do not edit by hand.
# Add in HA: Settings -> Dashboards -> Add dashboard -> New dashboard from scratch ->
# (three dots) Edit -> Raw configuration editor -> paste this file.
title: Hotel Sense
views:
  - title: Номера
    path: rooms
    icon: mdi:bed
    type: masonry
    cards:
{_indent(cards, 6)}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--rooms", nargs="*", default=DEFAULT_ROOMS)
    parser.add_argument("--common", nargs="*", default=DEFAULT_COMMON)
    args = parser.parse_args(argv)
    sys.stdout.write(build_dashboard(args.rooms, args.common))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
